<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE scatterBrain [
<!ELEMENT scatterBrain (Parameters+,Experiment)>
<!ELEMENT Parameters (PVMap,DetectorMap,MaskMap,CONFIGURATION+)>
<!ELEMENT Experiment (LOGLINE)*>
<!ELEMENT PVMap (PV)*>
<!ELEMENT DetectorMap (DETECTORDEF)*>
<!ELEMENT MaskMap (USERMASK)*>
<!ELEMENT CONFIGURATION (CAMERADEFS,USERMASKS,COUNTERDEFS,NORMALISATION)>
<!ELEMENT LOGLINE (#PCDATA|COMMENT|TYPE)*>
<!ELEMENT PV EMPTY>
<!ELEMENT DETECTORDEF (#PCDATA)>
<!ELEMENT USERMASK (#PCDATA)>
<!ELEMENT CAMERADEFS EMPTY>
<!ELEMENT USERMASKS (#PCDATA)>
<!ELEMENT COUNTERDEFS EMPTY>
<!ELEMENT NORMALISATION EMPTY>
<!ELEMENT COMMENT (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>

<!ATTLIST scatterBrain FileVersion CDATA #IMPLIED>
<!ATTLIST CONFIGURATION NAME CDATA #IMPLIED>
<!ATTLIST CONFIGURATION LOADCONFIG CDATA #IMPLIED>
<!ATTLIST CONFIGURATION DATAPATH CDATA #IMPLIED>
<!ATTLIST PV ACQUIRE (true|false) #IMPLIED>
<!ATTLIST PV ACQUIREHIGH CDATA #IMPLIED>
<!ATTLIST PV ACQUIRELOW CDATA #IMPLIED>
<!ATTLIST PV LOG (true|false) #IMPLIED>
<!ATTLIST PV READ CDATA #IMPLIED>
<!ATTLIST PV SET CDATA #IMPLIED>
<!ATTLIST PV TRANS (true|false) #IMPLIED>
<!ATTLIST PV TRANSHIGH CDATA #IMPLIED>
<!ATTLIST PV TRANSLOW CDATA #IMPLIED>
<!ATTLIST USERMASK SHAPE (Polygon|Circle|Arc) #IMPLIED>
<!ATTLIST USERMASK MASKNAME CDATA #IMPLIED>
<!ATTLIST USERMASK AUTO (true|false) #IMPLIED>
<!ATTLIST USERMASK COLOUR CDATA #IMPLIED>
<!ATTLIST USERMASK LOCK (true|false) #IMPLIED>
<!ATTLIST DETECTORDEF BASEPV CDATA #IMPLIED>
<!ATTLIST DETECTORDEF CAMPV CDATA #IMPLIED>
<!ATTLIST DETECTORDEF IMAGEPV CDATA #IMPLIED>
<!ATTLIST DETECTORDEF LOGFILEPV CDATA #IMPLIED>
<!ATTLIST DETECTORDEF FILEPV CDATA #IMPLIED>
<!ATTLIST DETECTORDEF XSIZE CDATA #IMPLIED>
<!ATTLIST DETECTORDEF YSIZE CDATA #IMPLIED>
<!ATTLIST DETECTORDEF PIXELSIZE CDATA #IMPLIED>
<!ATTLIST DETECTORDEF CONTROL CDATA #IMPLIED>
<!ATTLIST DETECTORDEF SOFTWARETRIGGER CDATA #IMPLIED>
<!ATTLIST DETECTORDEF AUTOLOAD CDATA #IMPLIED>
<!ATTLIST DETECTORDEF ROTATION CDATA #IMPLIED>
<!ATTLIST DETECTORDEF ACTIVE CDATA #IMPLIED>
<!ATTLIST CAMERADEFS DETECTOR CDATA #IMPLIED>
<!ATTLIST CAMERADEFS BEAMX CDATA #IMPLIED>
<!ATTLIST CAMERADEFS BEAMY CDATA #IMPLIED>
<!ATTLIST CAMERADEFS LENGTH CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPANGLE CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPWIDTH CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPRADIUS CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPACTIVE CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPOFFSETX CDATA #IMPLIED>
<!ATTLIST CAMERADEFS STOPOFFSETY CDATA #IMPLIED>
<!ATTLIST CAMERADEFS WAVELENGTH CDATA #IMPLIED>
<!ATTLIST CAMERADEFS WAXSANGLE CDATA #IMPLIED>
<!ATTLIST COUNTERDEFS BEAMSTOP CDATA #IMPLIED>
<!ATTLIST COUNTERDEFS INCIDENT CDATA #IMPLIED>
<!ATTLIST COUNTERDEFS TRANSMISSION CDATA #IMPLIED>
<!ATTLIST NORMALISATION ABSCAL CDATA #IMPLIED>
<!ATTLIST NORMALISATION USEABSCAL CDATA #IMPLIED>
<!ATTLIST NORMALISATION I0NORM CDATA #IMPLIED>
<!ATTLIST NORMALISATION IBSNORM CDATA #IMPLIED>
<!ATTLIST NORMALISATION NORMTYPE CDATA #IMPLIED>
<!ATTLIST COMMENT ATTACHMENT CDATA #IMPLIED>
<!ATTLIST LOGLINE USB_TEMP_T2 CDATA #IMPLIED>
<!ATTLIST LOGLINE GAPLESS_MODE CDATA #IMPLIED>
<!ATTLIST LOGLINE MCS_ELAPSED_REAL CDATA #IMPLIED>
<!ATTLIST LOGLINE SAXSDETECTOR_CAM_STRING_FROM_SERVER CDATA #IMPLIED>
<!ATTLIST LOGLINE SAXSDETECTOR_CAM_NUM_IMAGES CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_4_FINALGUARD_Y_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_4_FINALGUARD_X_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_3_ANTISCATTER_Y_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_3_ANTISCATTER_X_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_1_FLUX_Y_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE SLIT_1_FLUX_X_WIDTH CDATA #IMPLIED>
<!ATTLIST LOGLINE FDBK_CENTRE_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE FDBK_CENTRE_X CDATA #IMPLIED>
<!ATTLIST LOGLINE FDBK_PRE_CENTRE_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE FDBK_PRE_CENTRE_X CDATA #IMPLIED>
<!ATTLIST LOGLINE VERTICAL_FOCUS_FINE_PITCH CDATA #IMPLIED>
<!ATTLIST LOGLINE HORIZONTAL_FOCUS_FINE_PITCH CDATA #IMPLIED>
<!ATTLIST LOGLINE BCT_IO_AI_2 CDATA #IMPLIED>
<!ATTLIST LOGLINE BCT_IO_AI_1 CDATA #IMPLIED>
<!ATTLIST LOGLINE UNDULATOR_GAP CDATA #IMPLIED>
<!ATTLIST LOGLINE SI111_MONOCHROMATOR_XTAL2_PERP CDATA #IMPLIED>
<!ATTLIST LOGLINE SI111_MONOCHROMATOR_ENERGY CDATA #IMPLIED>
<!ATTLIST LOGLINE SPARE_GSAXS_CHANNELS_OMG CDATA #IMPLIED>
<!ATTLIST LOGLINE SPARE_GSAXS_CHANNELS_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE SPARE_GSAXS_CHANNELS_X CDATA #IMPLIED>
<!ATTLIST LOGLINE GSAXS_RIG_CHI CDATA #IMPLIED>
<!ATTLIST LOGLINE GSAXS_RIG_PHI CDATA #IMPLIED>
<!ATTLIST LOGLINE GSAXS_RIG_OMEGA CDATA #IMPLIED>
<!ATTLIST LOGLINE GSAXS_RIG_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE GSAXS_RIG_X CDATA #IMPLIED>
<!ATTLIST LOGLINE BEAMSTOP_STAGES_ROTN CDATA #IMPLIED>
<!ATTLIST LOGLINE BEAMSTOP_STAGES_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE BEAMSTOP_STAGES_X CDATA #IMPLIED>
<!ATTLIST LOGLINE PILATUS_2M_SAXS_DETECTOR_MOTION_Z CDATA #IMPLIED>
<!ATTLIST LOGLINE PILATUS_2M_SAXS_DETECTOR_MOTION_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE PILATUS_2M_SAXS_DETECTOR_MOTION_X CDATA #IMPLIED>
<!ATTLIST LOGLINE SAMPLE_TABLE_Y CDATA #IMPLIED>
<!ATTLIST LOGLINE SAMPLE_TABLE_X CDATA #IMPLIED>
<!ATTLIST LOGLINE GAPLESSPERSHOTIT CDATA #IMPLIED>
<!ATTLIST LOGLINE GAPLESSPERSHOTI0 CDATA #IMPLIED>
<!ATTLIST LOGLINE GAPLESSPERSHOTIBS CDATA #IMPLIED>
<!ATTLIST LOGLINE IT CDATA #IMPLIED>
<!ATTLIST LOGLINE I0 CDATA #IMPLIED>
<!ATTLIST LOGLINE IBS CDATA #IMPLIED>
<!ATTLIST LOGLINE EXPTIME CDATA #IMPLIED>
<!ATTLIST LOGLINE IMAGECOUNTER CDATA #IMPLIED>
<!ATTLIST LOGLINE NUMERICTIMESTAMP CDATA #IMPLIED>
<!ATTLIST LOGLINE TIMESTAMP CDATA #IMPLIED>
]>
<scatterBrain FileVersion=" 1.00000 ">

  <Parameters>
    <PVMap>
      <PV ACQUIRE="false" ACQUIREHIGH="10" ACQUIRELOW="-10" LOG="false" READ="SR13ID01HU02IOC01:SMPL_TBL_X_MTR.RBV" SET="SR13ID01HU02IOC01:SMPL_TBL_X_MTR.RBV" TRANS="false" TRANSHIGH="-8" TRANSLOW="-9"></PV>
    </PVMap>
    <DetectorMap>
      <DETECTORDEF AUTOLOAD="       1" BASEPV="SR13ID01PIL1:" CAMPV="cam1:" CONTROL="       1" FILEPV="cam1:" IMAGEPV="image1:" LOGFILEPV="" PIXELSIZE="      0.17200000" ROTATION=" 2" SOFTWARETRIGGER="       1" XSIZE="         1475" YSIZE="        1679">Pilatus 2M</DETECTORDEF>
      <DETECTORDEF AUTOLOAD="       0" BASEPV="SR13ID01PIL2:" CAMPV="cam1:" CONTROL="       1" FILEPV="cam1:" IMAGEPV="image1:" LOGFILEPV="" PIXELSIZE="      0.17200000" ROTATION=" 3" SOFTWARETRIGGER="       0" XSIZE="         487" YSIZE="         195">Pilatus 100K</DETECTORDEF>
    </DetectorMap>
    <MaskMap>
      <USERMASK AUTO="false" COLOUR="[0,0,0]" LOCK="false" MASKNAME="Frame part 1" SHAPE="Polygon">[486.000,486.000,-1.00000,-1.00000,486.000,486.000,-1.00000,-1.00000,486.000,486.000,-1.00000,-1.00000,486.000,486.000,-1.00000,-1.00000,486.000,486.000,495.000,495.000,1476.00,1476.00,495.000,495.000,1476.00,1476.00,495.000,495.000,1476.00,1476.00,495.000,495.000,1476.00,1476.00,495.000,495.000][-1.00000,193.000,193.000,213.000,213.000,406.000,406.000,425.000,425.000,617.000,617.000,637.000,637.000,830.000,830.000,849.000,849.000,1680.00,1680.00,849.000,849.000,830.000,830.000,637.000,637.000,617.000,617.000,425.000,425.000,406.000,406.000,213.000,213.000,193.000,193.000,-1.00000]</USERMASK>
      <USERMASK AUTO="false" COLOUR="[0,0,0]" LOCK="false" MASKNAME="Frame part 2" SHAPE="Polygon">[980.000,980.000,-1.00000,-1.00000,980.000,980.000,-1.00000,-1.00000,980.000,980.000,-1.00000,-1.00000,980.000,980.000,989.000,989.000,1476.00,1476.00,989.000,989.000,1476.00,1476.00,989.000,989.000,1476.00,1476.00,989.000,989.000][-1.00000,1042.00,1042.00,1061.00,1061.00,1254.00,1254.00,1273.00,1273.00,1466.00,1466.00,1485.00,1485.00,1680.00,1680.00,1485.00,1485.00,1466.00,1466.00,1273.00,1273.00,1254.00,1254.00,1061.00,1061.00,1042.00,1042.00,-1.00000]</USERMASK>
      <USERMASK AUTO="false" COLOUR="[0,0,0]" LOCK="false" MASKNAME="Mask  3" SHAPE="Polygon">[876.000,871.000,871.000,876.000][1220.00,1220.00,1223.00,1223.00]</USERMASK>
      <USERMASK AUTO="false" COLOUR="[0,0,0]" LOCK="false" MASKNAME="Mask  4" SHAPE="Polygon">[64.0000,-5.00000,-4.00000,64.0000][0.000000,-2.00000,40.0000,22.0000]</USERMASK>
      <USERMASK AUTO="true" COLOUR="[201,178,236]" LOCK="false" MASKNAME="Mask  5" SHAPE="Circle">[0.000000,0.000000,2000.00,0.000000,280.000,260.000]</USERMASK>
      <USERMASK AUTO="true" COLOUR="[160,255,160]" LOCK="false" MASKNAME="Mask  6" SHAPE="Circle">[0.000000,0.000000,2000.00,0.000000,190.000,170.000]</USERMASK>
    </MaskMap>
    <CONFIGURATION DATAPATH="Z:/Cycle_2024_1/Tran_21019/FeFF_WhitefieldIonChamberEnergyScan_Att0_24042024_4_tenflux4/images/" LOADCONFIG="" NAME="SAXS">
      <CAMERADEFS BEAMX="      857.440" BEAMY="      1194.07" DETECTOR="Pilatus 2M" LENGTH="      3000.00" STOPACTIVE="       1" STOPANGLE="      90.0000" STOPOFFSETX="     0.000000" STOPOFFSETY="     0.000000" STOPRADIUS="      14.0000" STOPWIDTH="      27.0000" WAVELENGTH="      1.07812" WAXSANGLE="     0.000000"></CAMERADEFS>
      <USERMASKS>[Frame part 1,Frame part 2,Mask  3,Mask  4,Mask  5,Mask  6][       1,       1,       1,       1,       0,       0]</USERMASKS>
      <COUNTERDEFS BEAMSTOP="IBS" INCIDENT="I0" TRANSMISSION="IT"></COUNTERDEFS>
      <NORMALISATION ABSCAL="   0.00144455" I0NORM="      100000." IBSNORM="      100000." NORMTYPE="       0" USEABSCAL="       1"></NORMALISATION>
    </CONFIGURATION>
    <CONFIGURATION DATAPATH="Z:/Cycle_2024_1/Tran_21019/FeFF_WhitefieldIonChamberEnergyScan_Att0_24042024_4_tenflux4/images/" LOADCONFIG="DETECTOR1" NAME="SAXS_5m">
      <CAMERADEFS BEAMX="      857.440" BEAMY="      1198.07" DETECTOR="Pilatus 2M" LENGTH="      5000.00" STOPACTIVE="       1" STOPANGLE="      90.0000" STOPOFFSETX="     0.000000" STOPOFFSETY="     0.000000" STOPRADIUS="      14.0000" STOPWIDTH="      27.0000" WAVELENGTH="      1.07812" WAXSANGLE="     0.000000"></CAMERADEFS>
      <USERMASKS>[Frame part 1,Frame part 2,Mask  3,Mask  4,Mask  5,Mask  6][       1,       1,       1,       1,       0,       0]</USERMASKS>
      <COUNTERDEFS BEAMSTOP="" INCIDENT="" TRANSMISSION=""></COUNTERDEFS>
      <NORMALISATION ABSCAL="   0.00144455" I0NORM="      100000." IBSNORM="      100000." NORMTYPE="       0" USEABSCAL="       1"></NORMALISATION>
    </CONFIGURATION>
  </Parameters>

  <Experiment>
  </Experiment>

</scatterBrain>
